# Fichier : .streamlit/secrets.toml.example
# CECI EST UN MODÈLE. NE METTEZ PAS VOS VRAIES CLÉS ICI.
# Copiez ce fichier en "secrets.toml" pour votre développement local.

OPENAI_API_KEY = "sk-..."
FERNET_KEY = "votre-cle-de-chiffrement-ici"
WEB_API_KEY = "AIzaSy..."

[database]
instance_connection_name = "projet:region:instance"
db_user = "postgres"
db_pass = "mot-de-passe-de-la-base-de-donnees"
db_name = "app_data"

[firebase_service_account]
type = "service_account"
project_id = "..."
private_key_id = "..."
private_key = "-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n"
client_email = "..."
# ... etc.