# Fichier : .streamlit/secrets.toml (Version finale et correcte)

OPENAI_API_KEY = "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"
FERNET_KEY = "1VqqHEc6ahodPtxJ3F_7Ml2WPQYUKwHMr8ig04XTaEo="
WEB_API_KEY = "AIzaSyBwgHz1iqImuDgsLk1J1D3BjpRMWLFIknk"

[database]
instance_connection_name = "odoo-ai-transformer:europe-west9:odoo-ai-transformer-db"
db_user = "postgres"
db_pass = "Cluso11235813!"
db_name = "app_data"

[stripe]
secret_key = "sk_test_51Rr3oICIiBkYnbb0zMVSrs8LCy5kHVGVsaOWxcWeVyHgFs9NEeWgZPNhWKyYOrTJt5o1xtasr2Qs627HRuNBZNb5004PBc32G0"
price_id = "prod_Smd6TgDUkmKVRs"

# NOUVELLE SECTION MISE À JOUR
[firebase_service_account]
type = "service_account"
project_id = "odoo-ai-transformer"
private_key_id = "7fdefd85834ad59aca1479319163d0a51be8aa68"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmo4EGtsi4Z7C+\nixt8QJJ9OMTGasXWZMQor4Dm1jjfBQ4SEw5A69nucMx6AGiAnSJxQfgNIad6IWM/\n16dHyFTBjFUzbN908oLchcmxjBKb4i2CAww4oAbNFXyxf7mRoJN+/Vzd6GKSXlhD\n8Th14lhBdqISA9Z3QvJuq0wpIDfUYJfJTefCNLzDfLCR8I2L6DS7cDq2mU4PU8S2\npI7yRUZQLJxC2ZSyTrKuzqHAK3FKU2scka/Z9uSjiBTkNPa7/OynyJEqjrESUwzW\nw63wQ08zUojJksXoJ3iYA8I20MGfFWMWHUnF4ZKhj0t9K8rhRf0NRw5+4tbNAsd7\n9o6trDnhAgMBAAECggEAA+F8NArTWmpAg8VS3EV6KbWup33Dc759kest42yLCrRr\ntKZq9b528pH/76K145sWr3BgJA1r9SsAneeOo9wlVSuC27q9R7FS4w3eluaVZRcS\n7YRLYZF9mfd5I60cF7T0pg123EyEi4fsOcU1wDnNVUmv6XxnB/iNQhpeoLNKv2Hd\nCEs6ZrKoxuPdzQfunkN+Ws1x1BekMVpHPDM5FOrxQ9leTLryyZgIWdOQccU/xCAE\nH0yo1n5F5vRgoO7XQ5R9R5Ll0woumhhMPQrJzTek3G+Cpmh6GGhaEtW/wgFNCH1z\nnZMXk3ujKA7n3XmyWUNzpqqaEzIFBlYtPdZRs5BYfQKBgQDgqgAvRqKbOpUMk9AW\n1iYWgVA4Vlt9ru4yv279RneWaPweB4Okwaj/SFBnrRfECN9w3MZyqAqSfJHiuBc1\nHYnnDBnQlQGxsXe1wXzsJu57HheKHDawC8DUeTtPPA5KD+U5fOE44V58/WWFT6zH\nXEJ7N2rCCuDj7j73Amqt9Ho/9wKBgQC94ZymbRcbKRHK2MSfVBsnleA6OyfS/Ccy\nzGRdJft2MY4HxKYV+CI9uV2JCK7vJ/bbJrOgklVYJvnNrmDIyorZAxxw8E5nP1+j\nOIKd3GxncTiGiTc4+zvZu03FOSEyafJ/LoBaI7HdeQAsy1tVDsh3N9kYHCmtxGHm\npKZw7csO5wKBgCncIwqr+5I2uRzN0cDfh9s7nunQVV22oVU9S/3PCmsxBoDF36Zs\nGwPtwmV+3+W7zX4m9KbaXpXqtffrWw+fgFlXbNvrV5R3P5nTAmax3k98TOCD30Cv\n/+7W49EgnHz6Nzid5w0FGOjrAeZz8Pp4Wz7AFZkwE7UEaCD4B06ANeMDAoGAAkQE\n6H94vRw6WB9KCVSplklViZxXF09m8FY8BFiFrZ1dwn34NV7mmbHyicYOwE/LxEWr\n8wiL+CdO58Ni6EJycbB10GstpFG/RGVSOav9pyZUtFZC0G0/A5QWk3nhCYb2G8pk\nQa8XWjstY1tx1Yv9nF6QOpdrb+Vd/bCNQ9+ygpUCgYAZq/M/Lb0kWW9iHFewBn3P\ngUpj1jTdlsAUK9L4n+b2RuzOX5BZVMnagSy+9C1mDI4V68fdmnIq4Ta3Ln7vKWoP\n43/rOctwsZpgViGFHkjBJcto11UiLJp+v4pCWEGFyP9g0xrhPL79vD9Kk/vfTRe7\nrvN/7dNwDeuIIFD+fqR6bg==\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@odoo-ai-transformer.iam.gserviceaccount.com"
client_id = "104567332608784718317"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40odoo-ai-transformer.iam.gserviceaccount.com"
universe_domain = "googleapis.com"